namespace: argocd

project: default

destination:
  name: in-cluster
  namespace: '{{ .name }}'

charts:
- name: cert-manager
  chart: cert-manager
  repoUrl: https://charts.jetstack.io
  version: 'v1.12.0'
